plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.mod_group_id

base {
	archivesName = "[${project.minecraft_version}-Fabric] ${project.mod_name}"
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
	maven { url = "https://mvn.devos.one/releases" } // Porting Lib releases
	maven { url = "https://mvn.devos.one/snapshots" } // Create and several dependencies
	maven { url = "https://maven.tterrag.com/" } // Flywheel
	maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
	maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" } // Forge Config API Port
	maven { // Fabric ASM for Porting Lib
		url = "https://jitpack.io/"
		content { includeGroupAndSubgroups("com.github") }
	}
	maven { url = "https://maven.shedaniel.me" } // Cloth Config, REI
	maven { url = "https://maven.blamejared.com" } // JEI
	maven { url = "https://maven.terraformersmc.com/releases" } // Mod Menu, EMI
    maven { url = "https://maven.createmod.net" } // Ponder
    maven { //curse maven
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

configurations.configureEach {
	resolutionStrategy {
		// make sure the desired version of loader is used. Sometimes old versions are pulled in transitively.
		force("net.fabricmc:fabric-loader:${project.loader_version}")
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.parchment_version}@zip")
    }
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	
    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.config_port_version}"
	modCompileOnly "com.simibubi.create:create-fabric-${project.create_mc_version}:${project.create_version}"
   	modCompileOnly "io.github.fabricators_of_create.Porting-Lib:core:${project.porting_lib_version}"
   	modCompileOnly "io.github.fabricators_of_create.Porting-Lib:data:${project.porting_lib_version}"
   	modCompileOnly "io.github.fabricators_of_create.Porting-Lib:model_generators:${project.porting_lib_version}"
   	modCompileOnly "io.github.fabricators_of_create.Porting-Lib:model_materials:${project.porting_lib_version}"
   	modCompileOnly "io.github.fabricators_of_create.Porting-Lib:utility:${project.porting_lib_version}"
	modApi "curse.maven:continuity-531351:${project.continuity_file}" //Continuity
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	// withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
}

loom {
	accessWidenerPath = file("src/main/resources/additionalplacements.accesswidener")
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = "${project.mod_id}-fabric-${project.minecraft_version}"
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
