# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Gradle Versions
moddevgradle_version=2.0.88

# Minecraft Properties
minecraft_version=1.21
minecraft_version_range=[1.21,1.21.3)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# NeoForge Properties
neo_version=21.0.167
neo_version_range=[21,)
loader_version_range=[1,)

# Mod Properties
mod_id=additionalplacements
mod_name=Additional Placements
mod_license=MIT
mod_version=2.3.0
mod_group_id=com.firemerald.additionalplacements
mod_authors=FirEmerald
mod_description=Adds additional placements for blocks:\nSlabs can be placed vertically.\nStairs can be placed vertically.\nCarpets can be placed on walls and ceilings.\nPressure plates can be placed on walls and ceilings.

# Dependencies
balm_file=6447094
doubleslabs_file=3873442
kleeslabs_file=6147686
ctm_file=5587515
create_mc_version=1.21.1
create_version=6.0.4-53
ponder_version=1.0.46
flywheel_version=1.0.2
registrate_version=MC1.21-1.3.0+62

# Fabric Compat
fabric_version=3.4.0
continuity_version=3.0.0-beta.5
