# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Gradle Versions
forgegradle_version=[6.0,6.2)
mixingradle_version=0.7.+
librarian_version=1.+

# Minecraft Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
parchment_version=2023.09.03-1.20.1

# Forge Properties
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

# Mod Properties
mod_id=additionalplacements
mod_name=Additional Placements
mod_license=MIT
mod_version=2.3.1
mod_group_id=com.firemerald.additionalplacements
mod_authors=FirEmerald
mod_description=Adds additional placements for blocks:\nSlabs can be placed vertically.\nStairs can be placed vertically.\nCarpets can be placed on walls and ceilings.\nPressure plates can be placed on walls and ceilings.

# Dependencies
mixin_version=0.8.5
balm_file=6520552
doubleslabs_file=3873442
kleeslabs_file=6226684
ctm_file=5983309
create_mc_version=1.20.1
create_version=6.0.4-79
ponder_version=1.0.52
flywheel_version=1.0.2
registrate_version=MC1.20-1.3.3
mixinextras_version=0.4.1

# Fabric Compat
fabric_version=3.2.1
continuity_version=3.0.0-beta.5
