# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Gradle Versions
forgegradle_version=[6.0,6.2)
mixingradle_version=0.7.+
librarian_version=1.+

# Minecraft Properties
minecraft_version=1.19.2
minecraft_version_range=[1.19.2,1.19.4)
parchment_version=2022.11.27-1.19.2

# Forge Properties
forge_version=43.5.0
forge_version_range=[43,)
loader_version_range=[43,)

# Mod Properties
mod_id=additionalplacements
mod_name=Additional Placements
mod_license=MIT
mod_version=2.3.1
mod_group_id=com.firemerald.additionalplacements
mod_authors=FirEmerald
mod_description=Adds additional placements for blocks:\nSlabs can be placed vertically.\nStairs can be placed vertically.\nCarpets can be placed on walls and ceilings.\nPressure plates can be placed on walls and ceilings.

# Dependencies
mixin_version=0.8.5
balm_file=4751735
doubleslabs_file=3873442
kleeslabs_file=4510538
create_file=5797604
flywheel_mc_version=1.19.2
flywheel_version=0.6.11-22
