modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/issues"
[[mods]]
modId="additionalplacements"
version="${file.jarVersion}"
displayName="Additional Placements"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/additional-placements" #optional
logoFile="additionalplacements.png"
credits="FirEmerald"
authors="FirEmerald"
description='''
Adds additional placements for blocks:
Slabs can be placed vertically.
Stairs can be placed vertically.
Carpets can be placed on walls and ceilings.
'''
[[dependencies.additionalplacements]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
